#pragma once
#ifndef FILE_Int_NOVA
#define FILE_Int_NOVA

typedef struct nova_standard_primitive_number_NovaInt nova_standard_primitive_number_NovaInt;

#include <Nova.h>
#include <ExceptionHandler.h>
#include <nova/standard/exception/nova_standard_exception_NovaExceptionData.h>
#include <nova/standard/exception/nova_standard_exception_NovaException.h>
#include <nova/standard/exception/nova_standard_exception_NovaDivideByZeroException.h>
#include <nova/standard/io/nova_standard_io_NovaConsole.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaNumber.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaByte.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaShort.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaInt.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaLong.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaFloat.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaDouble.h>
#include <nova/standard/primitive/nova_standard_primitive_NovaNull.h>
#include <nova/standard/primitive/nova_standard_primitive_NovaChar.h>
#include <nova/standard/primitive/nova_standard_primitive_NovaBool.h>
#include <nova/standard/gc/nova_standard_gc_NovaGC.h>
#include <nova/standard/nova_standard_NovaObject.h>
#include <nova/standard/nova_standard_NovaString.h>
#include <nova/standard/nova_standard_NovaSystem.h>
#include <nova/standard/nova_standard_NovaMath.h>

typedef struct nova_VTable_nova_standard_primitive_number_NovaInt
{
	nova_standard_NovaString* (*nova_standard_primitive_number_NovaInt_Novavirtual2_toString)(nova_standard_primitive_number_NovaInt*, nova_standard_exception_NovaExceptionData*);
	char (*nova_standard_NovaObject_Novavirtual0_equals)(nova_standard_NovaObject*, nova_standard_exception_NovaExceptionData*, nova_standard_NovaObject*);
	int (*nova_standard_primitive_number_NovaInt_static_Novavirtual0_numDigits)(nova_standard_primitive_number_NovaInt*, nova_standard_exception_NovaExceptionData*, int);
	nova_standard_NovaString* (*nova_standard_primitive_number_NovaInt_static_Novavirtual1_toString)(nova_standard_primitive_number_NovaInt*, nova_standard_exception_NovaExceptionData*, int);
} nova_VTable_nova_standard_primitive_number_NovaInt;

CCLASS_CLASS
(
	nova_standard_primitive_number_NovaInt, 
	
	nova_VTable_nova_standard_primitive_number_NovaInt* vtable;
	int nova_standard_primitive_number_NovaInt_Novavalue;
)

void nova_standard_primitive_number_NovaIntNova_init_static(nova_standard_exception_NovaExceptionData* exceptionData);
nova_standard_primitive_number_NovaInt* nova_standard_primitive_number_NovaInt_Novaconstruct(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData, int l0_Novavalue);
void nova_del_Int(nova_standard_primitive_number_NovaInt** this, nova_standard_exception_NovaExceptionData* exceptionData);
void nova_standard_primitive_number_NovaInt_Novathis(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData, int l0_Novavalue);
int nova_standard_primitive_number_NovaInt_static_Nova0_numDigits(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData, int l0_Novanumber);
nova_standard_NovaString* nova_standard_primitive_number_NovaInt_static_Nova1_toString(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData, int l0_Novavalue);
nova_standard_NovaString* nova_standard_primitive_number_NovaInt_Nova2_toString(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData);
int nova_standard_primitive_number_NovaInt_NovaparseInt(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_NovaString* l0_Novanum);
void nova_standard_primitive_number_NovaInt_Novasuper(nova_standard_primitive_number_NovaInt* this, nova_standard_exception_NovaExceptionData* exceptionData);

#endif