#pragma once
#ifndef FILE_Bounds_NOVA
#define FILE_Bounds_NOVA

typedef struct nova_standard_datastruct_NovaBounds nova_standard_datastruct_NovaBounds;

#include <Nova.h>
#include <ExceptionHandler.h>
#include <nova/standard/exception/nova_standard_exception_NovaExceptionData.h>
#include <nova/standard/exception/nova_standard_exception_NovaException.h>
#include <nova/standard/exception/nova_standard_exception_NovaDivideByZeroException.h>
#include <nova/standard/io/nova_standard_io_NovaConsole.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaNumber.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaByte.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaShort.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaInt.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaLong.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaFloat.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_NovaDouble.h>
#include <nova/standard/primitive/nova_standard_primitive_NovaNull.h>
#include <nova/standard/primitive/nova_standard_primitive_NovaChar.h>
#include <nova/standard/primitive/nova_standard_primitive_NovaBool.h>
#include <nova/standard/gc/nova_standard_gc_NovaGC.h>
#include <nova/standard/nova_standard_NovaObject.h>
#include <nova/standard/nova_standard_NovaString.h>
#include <nova/standard/nova_standard_NovaSystem.h>
#include <nova/standard/nova_standard_NovaMath.h>

typedef struct nova_VTable_nova_standard_datastruct_NovaBounds
{
	nova_standard_NovaString* (*nova_standard_datastruct_NovaBounds_Novavirtual0_toString)(nova_standard_datastruct_NovaBounds*, nova_standard_exception_NovaExceptionData*);
	char (*nova_standard_datastruct_NovaBounds_Novavirtual0_equals)(nova_standard_datastruct_NovaBounds*, nova_standard_exception_NovaExceptionData*, nova_standard_datastruct_NovaBounds*);
} nova_VTable_nova_standard_datastruct_NovaBounds;

CCLASS_CLASS
(
	nova_standard_datastruct_NovaBounds, 
	
	nova_VTable_nova_standard_datastruct_NovaBounds* vtable;
	int nova_standard_datastruct_NovaBounds_Novastart;
	int nova_standard_datastruct_NovaBounds_Novaend;
)

nova_standard_datastruct_NovaBounds* nova_standard_datastruct_NovaBounds_Novaconstruct(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, int l0_Novastart, int l0_Novaend);
void nova_del_Bounds(nova_standard_datastruct_NovaBounds** this, nova_standard_exception_NovaExceptionData* exceptionData);
void nova_standard_datastruct_NovaBounds_Novathis(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, int l0_Novastart, int l0_Novaend);
nova_standard_NovaString* nova_standard_datastruct_NovaBounds_NovaextractString(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_NovaString* l0_Novasource);
nova_standard_NovaString* nova_standard_datastruct_NovaBounds_NovaextractPreString(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_NovaString* l0_Novasource);
nova_standard_NovaString* nova_standard_datastruct_NovaBounds_NovaextractPostString(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_NovaString* l0_Novasource);
nova_standard_NovaString* nova_standard_datastruct_NovaBounds_NovatrimString(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_NovaString* l0_Novasource);
char nova_standard_datastruct_NovaBounds_NovaisEndless(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
char nova_standard_datastruct_NovaBounds_NovaisOptional(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
int nova_standard_datastruct_NovaBounds_Novalength(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
char nova_standard_datastruct_NovaBounds_NovaisValid(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
void nova_standard_datastruct_NovaBounds_NovasetInvalid(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
char nova_standard_datastruct_NovaBounds_Nova0_equals(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_datastruct_NovaBounds* l0_Novabounds);
nova_standard_NovaString* nova_standard_datastruct_NovaBounds_Nova0_toString(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
void nova_standard_datastruct_NovaBounds_NovacloneTo(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData, nova_standard_datastruct_NovaBounds* l0_Novabounds);
nova_standard_datastruct_NovaBounds* nova_standard_datastruct_NovaBounds_Novaclone(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);
void nova_standard_datastruct_NovaBounds_Novasuper(nova_standard_datastruct_NovaBounds* this, nova_standard_exception_NovaExceptionData* exceptionData);

#endif