#pragma once
#ifndef FILE_nova_standard_datastruct_Nova_ArrayList_NOVA
#define FILE_nova_standard_datastruct_Nova_ArrayList_NOVA

typedef struct nova_standard_datastruct_Nova_ArrayList nova_standard_datastruct_Nova_ArrayList;
typedef struct nova_standard_Nova_Object nova_standard_Nova_Object;
typedef struct nova_standard_exception_Nova_ExceptionData nova_standard_exception_Nova_ExceptionData;

typedef char (*l0_1_Nova_filterFunc)(void*, nova_standard_exception_Nova_ExceptionData*, nova_standard_Nova_Object*);
typedef char (*l0_2_Nova_filterFunc)(void*, nova_standard_exception_Nova_ExceptionData*, nova_standard_Nova_Object*);
typedef char (*l0_3_Nova_filterFunc)(void*, nova_standard_exception_Nova_ExceptionData*, nova_standard_Nova_Object*);

#include <Nova.h>
#include <ExceptionHandler.h>
#include <InterfaceVTable.h>
#include <nova/standard/exception/nova_standard_exception_Nova_ExceptionData.h>
#include <nova/standard/exception/nova_standard_exception_Nova_Exception.h>
#include <nova/standard/exception/nova_standard_exception_Nova_DivideByZeroException.h>
#include <nova/standard/io/nova_standard_io_Nova_Console.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Number.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Byte.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Short.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Int.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Long.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Float.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Double.h>
#include <nova/standard/primitive/nova_standard_primitive_Nova_Null.h>
#include <nova/standard/primitive/number/nova_standard_primitive_number_Nova_Char.h>
#include <nova/standard/primitive/nova_standard_primitive_Nova_Bool.h>
#include <nova/standard/datastruct/nova_standard_datastruct_Nova_Array.h>
#include <nova/standard/gc/nova_standard_gc_Nova_GC.h>
#include <nova/standard/nova_standard_Nova_Object.h>
#include <nova/standard/nova_standard_Nova_String.h>
#include <nova/standard/nova_standard_Nova_System.h>
#include <nova/standard/math/nova_standard_math_Nova_Math.h>
#include <nova/standard/datastruct/nova_standard_datastruct_Nova_Enumerable.h>


typedef struct nova_standard_datastruct_Extension_VTable_ArrayList nova_standard_datastruct_Extension_VTable_ArrayList;
struct nova_standard_datastruct_Extension_VTable_ArrayList
{
	nova_Interface_VTable itable;
	long (*nova_standard_Nova_Object_virtual0_Nova_getHashCodeLong)(nova_standard_Nova_Object*, nova_standard_exception_Nova_ExceptionData*);
	nova_standard_Nova_String* (*nova_standard_Nova_Object_virtual0_Nova_toString)(nova_standard_Nova_Object*, nova_standard_exception_Nova_ExceptionData*);
	char (*nova_standard_Nova_Object_virtual0_Nova_equals)(nova_standard_Nova_Object*, nova_standard_exception_Nova_ExceptionData*, nova_standard_Nova_Object*);
	nova_standard_datastruct_Nova_ArrayList* (*nova_standard_datastruct_Nova_ArrayList_virtual_Nova_filter)(nova_standard_datastruct_Nova_ArrayList*, nova_standard_exception_Nova_ExceptionData*, l0_3_Nova_filterFunc l0_Nova_filterFunc, void* l0_ref_Nova_filterFunc);
};

extern nova_standard_datastruct_Extension_VTable_ArrayList nova_standard_datastruct_Extension_VTable_ArrayList_val;


CCLASS_CLASS
(
	nova_standard_datastruct_Nova_ArrayList, 
	
	nova_standard_datastruct_Extension_VTable_ArrayList* vtable;
	int nova_standard_datastruct_Nova_ArrayList_Nova_size;
	struct Private* prv;
)

void nova_standard_datastruct_Nova_ArrayListNova_init_static(nova_standard_exception_Nova_ExceptionData* exceptionData);
nova_standard_datastruct_Nova_ArrayList* nova_standard_datastruct_Nova_ArrayList_2_Nova_construct(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData);
nova_standard_datastruct_Nova_ArrayList* nova_standard_datastruct_Nova_ArrayList_3_Nova_construct(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_size);
void nova_standard_datastruct_Nova_ArrayList_Nova_destroy(nova_standard_datastruct_Nova_ArrayList** this, nova_standard_exception_Nova_ExceptionData* exceptionData);
void nova_standard_datastruct_Nova_ArrayList_2_Nova_this(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData);
void nova_standard_datastruct_Nova_ArrayList_3_Nova_this(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_size);
void nova_standard_datastruct_Nova_ArrayList_0_Nova_add(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_Nova_Object* l0_Nova_element);
void nova_standard_datastruct_Nova_ArrayList_1_Nova_add(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_index, nova_standard_Nova_Object* l0_Nova_element);
nova_standard_Nova_Object* nova_standard_datastruct_Nova_ArrayList_Nova_remove(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_index);
void nova_standard_datastruct_Nova_ArrayList_Nova_swap(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_index1, int l0_Nova_index2);
nova_standard_Nova_Object* nova_standard_datastruct_Nova_ArrayList_Nova_get(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_index);
void nova_standard_datastruct_Nova_ArrayList_Nova_set(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int l0_Nova_index, nova_standard_Nova_Object* l0_Nova_value);
nova_standard_Nova_Object** nova_standard_datastruct_Nova_ArrayList_Nova_toArray(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData);
nova_standard_datastruct_Nova_ArrayList* nova_standard_datastruct_Nova_ArrayList_Nova_filter(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData, l0_3_Nova_filterFunc l0_Nova_filterFunc, void* l0_ref_Nova_filterFunc);
char nova_standard_datastruct_Nova_ArrayList_Accessor_Nova_empty(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData);
void nova_standard_datastruct_Nova_ArrayList_Nova_super(nova_standard_datastruct_Nova_ArrayList* this, nova_standard_exception_Nova_ExceptionData* exceptionData);

#endif
