#include <precompiled.h>
#include <nova/standard/datastruct/nova_standard_datastruct_Nova_Enumerable.h>

nova_standard_datastruct_Extension_VTable_Enumerable nova_standard_datastruct_Extension_VTable_Enumerable_val =
{
	{
		0,
		0,
		0,
		(void(*)(nova_standard_datastruct_Nova_Enumerable*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_Nova_Enumerable_closure3_Nova_func nova_standard_datastruct_Nova_Enumerable_Nova_func, void* nova_standard_datastruct_Nova_Enumerable_ref_Nova_func))nova_standard_datastruct_Nova_Enumerable_0_Nova_forEach,
		(nova_standard_datastruct_Nova_Enumerable*(*)(nova_standard_datastruct_Nova_Enumerable*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_Nova_Enumerable_closure6_Nova_filterFunc nova_standard_datastruct_Nova_Enumerable_Nova_filterFunc, void* nova_standard_datastruct_Nova_Enumerable_ref_Nova_filterFunc))nova_standard_datastruct_Nova_Enumerable_0_Nova_filter,
		(nova_standard_datastruct_Nova_Enumerable*(*)(nova_standard_datastruct_Nova_Enumerable*, nova_standard_exception_Nova_ExceptionData*, int))nova_standard_datastruct_Nova_Enumerable_0_Nova_take,
		(nova_standard_datastruct_Nova_Enumerable*(*)(nova_standard_datastruct_Nova_Enumerable*, nova_standard_exception_Nova_ExceptionData*, int))nova_standard_datastruct_Nova_Enumerable_0_Nova_skip,
		0,
		0,
		0,
	},
	nova_standard_datastruct_Nova_Enumerable_0_Nova_forEach,
	nova_standard_datastruct_Nova_Enumerable_0_Nova_filter,
	nova_standard_datastruct_Nova_Enumerable_0_Nova_take,
	nova_standard_datastruct_Nova_Enumerable_0_Nova_skip,
};


void nova_standard_datastruct_Nova_EnumerableNova_init_static(nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	{
	}
}

void nova_standard_datastruct_Nova_Enumerable_0_Nova_forEach(nova_standard_datastruct_Nova_Enumerable* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Enumerable_closure3_Nova_func nova_standard_datastruct_Nova_Enumerable_Nova_func, void* nova_standard_datastruct_Nova_Enumerable_ref_Nova_func){}
nova_standard_datastruct_Nova_Enumerable* nova_standard_datastruct_Nova_Enumerable_0_Nova_filter(nova_standard_datastruct_Nova_Enumerable* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Enumerable_closure6_Nova_filterFunc nova_standard_datastruct_Nova_Enumerable_Nova_filterFunc, void* nova_standard_datastruct_Nova_Enumerable_ref_Nova_filterFunc){}
nova_standard_datastruct_Nova_Enumerable* nova_standard_datastruct_Nova_Enumerable_0_Nova_take(nova_standard_datastruct_Nova_Enumerable* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int nova_standard_datastruct_Nova_Enumerable_Nova_howMany){}
nova_standard_datastruct_Nova_Enumerable* nova_standard_datastruct_Nova_Enumerable_0_Nova_skip(nova_standard_datastruct_Nova_Enumerable* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int nova_standard_datastruct_Nova_Enumerable_Nova_howMany){}
