#include <precompiled.h>
#include <nova/standard/datastruct/nova_standard_datastruct_Nova_Node.h>

typedef struct
{
	/* Array<Object> array */ nova_standard_datastruct_list_Nova_Array** nova_standard_datastruct_Nova_Node_Nova_array;
} Context1;
typedef struct
{
	/* Array<Object> array */ nova_standard_datastruct_list_Nova_Array** nova_standard_datastruct_Nova_Node_Nova_array;
} Context2;
typedef struct
{
	/* Array<Object> array */ nova_standard_datastruct_list_Nova_Array** nova_standard_datastruct_Nova_Node_Nova_array;
} Context3;
typedef struct
{
	/* Array<Object> array */ nova_standard_datastruct_list_Nova_Array** nova_standard_datastruct_Nova_Node_Nova_array;
} Context4;
typedef struct
{
	/* Queue<Node<Object>, Node<Object>, Node<Object>, Node<Object>, Node<Object>, Node<Object>> queue */ nova_standard_datastruct_list_Nova_Queue** nova_standard_datastruct_Nova_Node_Nova_queue;
} Context5;


nova_standard_datastruct_Extension_VTable_Node nova_standard_datastruct_Extension_VTable_Node_val =
{
	{
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		(char(*)(nova_standard_operators_Nova_Equals*, nova_standard_exception_Nova_ExceptionData*, nova_standard_Nova_Object*))nova_standard_Nova_Object_0_Nova_equals,
		0,
		0,
		0,
	},
	nova_standard_Nova_Object_0_Nova_getHashCodeLong,
	nova_standard_datastruct_Nova_Node_0_Nova_toString,
	nova_standard_Nova_Object_0_Nova_equals,
};



char nova_standard_datastruct_Nova_Node_Nova_notNull(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova_value);
void nova_standard_datastruct_Nova_Node_1_Nova_preorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array);
nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_1_Nova_inorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array);
nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_1_Nova_postorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array);
nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_1_Nova_levelorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array);
void nova_standard_datastruct_Nova_Node_Nova_testLambda20(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context1* context);
void nova_standard_datastruct_Nova_Node_Nova_testLambda21(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context2* context);
void nova_standard_datastruct_Nova_Node_Nova_testLambda22(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context3* context);
void nova_standard_datastruct_Nova_Node_Nova_testLambda23(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context4* context);
nova_standard_datastruct_list_Nova_Array* generated9(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData);
void nova_standard_datastruct_Nova_Node_Nova_testLambda24(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context5* context);
void nova_standard_datastruct_Nova_Node_Nova_init_static(nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	{
	}
}

nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_0_Nova_Node(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	CCLASS_NEW(nova_standard_datastruct_Nova_Node, this,);
	this->vtable = &nova_standard_datastruct_Extension_VTable_Node_val;
	nova_standard_Nova_Object_Nova_super((nova_standard_Nova_Object*)this, exceptionData);
	nova_standard_datastruct_Nova_Node_Nova_super(this, exceptionData);
	
	{
		nova_standard_datastruct_Nova_Node_2_Nova_this(this, exceptionData);
	}
	
	return this;
}

nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_1_Nova_Node(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_Nova_Object* nova_standard_datastruct_Nova_Node_Nova_data)
{
	CCLASS_NEW(nova_standard_datastruct_Nova_Node, this,);
	this->vtable = &nova_standard_datastruct_Extension_VTable_Node_val;
	nova_standard_Nova_Object_Nova_super((nova_standard_Nova_Object*)this, exceptionData);
	nova_standard_datastruct_Nova_Node_Nova_super(this, exceptionData);
	
	{
		nova_standard_datastruct_Nova_Node_3_Nova_this(this, exceptionData, nova_standard_datastruct_Nova_Node_Nova_data);
	}
	
	return this;
}

nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_2_Nova_Node(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int nova_standard_datastruct_Nova_Node_Nova_numChildren)
{
	CCLASS_NEW(nova_standard_datastruct_Nova_Node, this,);
	this->vtable = &nova_standard_datastruct_Extension_VTable_Node_val;
	nova_standard_Nova_Object_Nova_super((nova_standard_Nova_Object*)this, exceptionData);
	nova_standard_datastruct_Nova_Node_Nova_super(this, exceptionData);
	
	{
		nova_standard_datastruct_Nova_Node_3_Nova_this(this, exceptionData, (nova_standard_Nova_Object*)(nova_standard_primitive_number_Nova_Int_Nova_Int(0, exceptionData, nova_standard_datastruct_Nova_Node_Nova_numChildren)));
	}
	
	return this;
}

nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_3_Nova_Node(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_Nova_Object* nova_standard_datastruct_Nova_Node_Nova_data, int nova_standard_datastruct_Nova_Node_Nova_numChildren)
{
	CCLASS_NEW(nova_standard_datastruct_Nova_Node, this,);
	this->vtable = &nova_standard_datastruct_Extension_VTable_Node_val;
	nova_standard_Nova_Object_Nova_super((nova_standard_Nova_Object*)this, exceptionData);
	nova_standard_datastruct_Nova_Node_Nova_super(this, exceptionData);
	
	{
		nova_standard_datastruct_Nova_Node_5_Nova_this(this, exceptionData, nova_standard_datastruct_Nova_Node_Nova_data, nova_standard_datastruct_Nova_Node_Nova_numChildren);
	}
	
	return this;
}

void nova_standard_datastruct_Nova_Node_Nova_destroy(nova_standard_datastruct_Nova_Node** this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	if (!*this)
	{
		return;
	}
	
	
	nova_standard_datastruct_list_Nova_Array_Nova_destroy(&(*this)->nova_standard_datastruct_Nova_Node_Nova_children, exceptionData);
	
	NOVA_FREE(*this);
}

void nova_standard_datastruct_Nova_Node_2_Nova_this(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	nova_standard_datastruct_Nova_Node_3_Nova_this(this, exceptionData, (nova_standard_Nova_Object*)((nova_standard_Nova_Object*)nova_null));
}

void nova_standard_datastruct_Nova_Node_3_Nova_this(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_Nova_Object* nova_standard_datastruct_Nova_Node_Nova_data)
{
	this->nova_standard_datastruct_Nova_Node_Nova_children = nova_standard_datastruct_list_Nova_Array_0_Nova_Array(0, exceptionData);
	this->nova_standard_datastruct_Nova_Node_Nova_data = nova_standard_datastruct_Nova_Node_Nova_data;
}

void nova_standard_datastruct_Nova_Node_4_Nova_this(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int nova_standard_datastruct_Nova_Node_Nova_numChildren)
{
	nova_standard_datastruct_Nova_Node_5_Nova_this(this, exceptionData, (nova_standard_Nova_Object*)((nova_standard_Nova_Object*)nova_null), nova_standard_datastruct_Nova_Node_Nova_numChildren);
}

void nova_standard_datastruct_Nova_Node_5_Nova_this(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_Nova_Object* nova_standard_datastruct_Nova_Node_Nova_data, int nova_standard_datastruct_Nova_Node_Nova_numChildren)
{
	this->nova_standard_datastruct_Nova_Node_Nova_children = nova_standard_datastruct_list_Nova_Array_1_Nova_Array(0, exceptionData, nova_standard_datastruct_Nova_Node_Nova_numChildren);
	this->nova_standard_datastruct_Nova_Node_Nova_data = nova_standard_datastruct_Nova_Node_Nova_data;
}

char nova_standard_datastruct_Nova_Node_Nova_notNull(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova_value)
{
	return nova_standard_datastruct_Nova_Node_Nova_value != (nova_standard_datastruct_Nova_Node*)nova_null;
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_0_Nova_preorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	nova_standard_datastruct_list_Nova_Array* l1_Nova_array = (nova_standard_datastruct_list_Nova_Array*)nova_null;
	
	l1_Nova_array = nova_standard_datastruct_list_Nova_Array_0_Nova_Array(0, exceptionData);
	nova_standard_datastruct_Nova_Node_1_Nova_preorder(this, exceptionData, l1_Nova_array);
	return l1_Nova_array;
}

void nova_standard_datastruct_Nova_Node_1_Nova_preorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array)
{
	Context1 contextArg23 = 
	{
		&nova_standard_datastruct_Nova_Node_Nova_array,
	};
	
	nova_standard_datastruct_list_Nova_Array_0_Nova_add(nova_standard_datastruct_Nova_Node_Nova_array, exceptionData, this->nova_standard_datastruct_Nova_Node_Nova_data);
	nova_standard_datastruct_list_Nova_List_virtual0_Nova_forEach((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_filter((nova_standard_datastruct_list_Nova_List*)(this->nova_standard_datastruct_Nova_Node_Nova_children), exceptionData, (nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc)&nova_standard_datastruct_Nova_Node_Nova_notNull, this, nova_null)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure3_Nova_func)&nova_standard_datastruct_Nova_Node_Nova_testLambda20, this, &contextArg23);
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_0_Nova_inorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	nova_standard_datastruct_list_Nova_Array* l1_Nova_array = (nova_standard_datastruct_list_Nova_Array*)nova_null;
	
	l1_Nova_array = nova_standard_datastruct_list_Nova_Array_0_Nova_Array(0, exceptionData);
	return nova_standard_datastruct_Nova_Node_1_Nova_inorder(this, exceptionData, l1_Nova_array);
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_1_Nova_inorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array)
{
	int l1_Nova_half = 0;
	Context2 contextArg24 = 
	{
		&nova_standard_datastruct_Nova_Node_Nova_array,
	};
	Context3 contextArg25 = 
	{
		&nova_standard_datastruct_Nova_Node_Nova_array,
	};
	
	l1_Nova_half = (int)(nova_standard_math_Nova_Math_Nova_ceil(0, exceptionData, this->nova_standard_datastruct_Nova_Node_Nova_children->nova_standard_datastruct_list_Nova_Array_Nova_count / 2.0));
	nova_standard_datastruct_list_Nova_List_virtual0_Nova_forEach((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_filter((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_take((nova_standard_datastruct_list_Nova_List*)(this->nova_standard_datastruct_Nova_Node_Nova_children), exceptionData, l1_Nova_half)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc)&nova_standard_datastruct_Nova_Node_Nova_notNull, this, nova_null)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure3_Nova_func)&nova_standard_datastruct_Nova_Node_Nova_testLambda21, this, &contextArg24);
	nova_standard_datastruct_list_Nova_Array_0_Nova_add(nova_standard_datastruct_Nova_Node_Nova_array, exceptionData, this->nova_standard_datastruct_Nova_Node_Nova_data);
	nova_standard_datastruct_list_Nova_List_virtual0_Nova_forEach((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_filter((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_skip((nova_standard_datastruct_list_Nova_List*)(this->nova_standard_datastruct_Nova_Node_Nova_children), exceptionData, l1_Nova_half)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc)&nova_standard_datastruct_Nova_Node_Nova_notNull, this, nova_null)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure3_Nova_func)&nova_standard_datastruct_Nova_Node_Nova_testLambda22, this, &contextArg25);
	return nova_standard_datastruct_Nova_Node_Nova_array;
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_0_Nova_postorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	nova_standard_datastruct_list_Nova_Array* l1_Nova_array = (nova_standard_datastruct_list_Nova_Array*)nova_null;
	
	l1_Nova_array = nova_standard_datastruct_list_Nova_Array_0_Nova_Array(0, exceptionData);
	return nova_standard_datastruct_Nova_Node_1_Nova_postorder(this, exceptionData, l1_Nova_array);
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_1_Nova_postorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array)
{
	Context4 contextArg26 = 
	{
		&nova_standard_datastruct_Nova_Node_Nova_array,
	};
	
	nova_standard_datastruct_list_Nova_List_virtual0_Nova_forEach((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_filter((nova_standard_datastruct_list_Nova_List*)(this->nova_standard_datastruct_Nova_Node_Nova_children), exceptionData, (nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc)&nova_standard_datastruct_Nova_Node_Nova_notNull, this, nova_null)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure3_Nova_func)&nova_standard_datastruct_Nova_Node_Nova_testLambda23, this, &contextArg26);
	nova_standard_datastruct_list_Nova_Array_0_Nova_add(nova_standard_datastruct_Nova_Node_Nova_array, exceptionData, this->nova_standard_datastruct_Nova_Node_Nova_data);
	return nova_standard_datastruct_Nova_Node_Nova_array;
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_0_Nova_levelorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	nova_standard_datastruct_list_Nova_Array* l1_Nova_array = (nova_standard_datastruct_list_Nova_Array*)nova_null;
	
	l1_Nova_array = nova_standard_datastruct_list_Nova_Array_0_Nova_Array(0, exceptionData);
	return nova_standard_datastruct_Nova_Node_1_Nova_levelorder(this, exceptionData, l1_Nova_array);
}

nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_1_Nova_levelorder(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova_array)
{
	nova_standard_datastruct_list_Nova_Queue* l1_Nova_queue = (nova_standard_datastruct_list_Nova_Queue*)nova_null;
	
	l1_Nova_queue = nova_standard_datastruct_list_Nova_Queue_1_Nova_Queue(0, exceptionData, generated9(this, exceptionData));
	while (!nova_standard_datastruct_list_Nova_Queue_Accessor_Nova_empty(l1_Nova_queue, exceptionData))
	{
		nova_standard_datastruct_Nova_Node* l1_Nova_current = (nova_standard_datastruct_Nova_Node*)nova_null;
		Context5 contextArg27 = 
		{
			&l1_Nova_queue,
		};
		
		l1_Nova_current = (nova_standard_datastruct_Nova_Node*)(nova_standard_datastruct_list_Nova_Queue_Nova_dequeue(l1_Nova_queue, exceptionData));
		nova_standard_datastruct_list_Nova_Array_0_Nova_add(nova_standard_datastruct_Nova_Node_Nova_array, exceptionData, l1_Nova_current->nova_standard_datastruct_Nova_Node_Nova_data);
		nova_standard_datastruct_list_Nova_List_virtual0_Nova_forEach((nova_standard_datastruct_list_Nova_List*)(nova_standard_datastruct_list_Nova_List_virtual0_Nova_filter((nova_standard_datastruct_list_Nova_List*)(l1_Nova_current->nova_standard_datastruct_Nova_Node_Nova_children), exceptionData, (nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc)&nova_standard_datastruct_Nova_Node_Nova_notNull, this, nova_null)), exceptionData, (nova_standard_datastruct_list_Nova_List_closure3_Nova_func)&nova_standard_datastruct_Nova_Node_Nova_testLambda24, this, &contextArg27);
	}
	return nova_standard_datastruct_Nova_Node_Nova_array;
}

nova_standard_Nova_String* nova_standard_datastruct_Nova_Node_0_Nova_toString(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	return (nova_standard_Nova_String*)(nova_standard_Nova_Object_virtual1_Nova_toString((nova_standard_Nova_Object*)(this->nova_standard_datastruct_Nova_Node_Nova_data), exceptionData));
}

void nova_standard_datastruct_Nova_Node_Nova_testLambda20(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context1* context)
{
	nova_standard_datastruct_Nova_Node_1_Nova_preorder(nova_standard_datastruct_Nova_Node_Nova__1, exceptionData, (*context->nova_standard_datastruct_Nova_Node_Nova_array));
}

void nova_standard_datastruct_Nova_Node_Nova_testLambda21(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context2* context)
{
	nova_standard_datastruct_Nova_Node_1_Nova_inorder(nova_standard_datastruct_Nova_Node_Nova__1, exceptionData, (*context->nova_standard_datastruct_Nova_Node_Nova_array));
}

void nova_standard_datastruct_Nova_Node_Nova_testLambda22(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context3* context)
{
	nova_standard_datastruct_Nova_Node_1_Nova_inorder(nova_standard_datastruct_Nova_Node_Nova__1, exceptionData, (*context->nova_standard_datastruct_Nova_Node_Nova_array));
}

void nova_standard_datastruct_Nova_Node_Nova_testLambda23(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context4* context)
{
	nova_standard_datastruct_Nova_Node_1_Nova_postorder(nova_standard_datastruct_Nova_Node_Nova__1, exceptionData, (*context->nova_standard_datastruct_Nova_Node_Nova_array));
}

nova_standard_datastruct_list_Nova_Array* generated9(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	nova_standard_datastruct_Nova_Node** l1_Nova_temp = (nova_standard_datastruct_Nova_Node**)nova_null;
	
	l1_Nova_temp = (nova_standard_datastruct_Nova_Node**)NOVA_MALLOC(sizeof(nova_standard_datastruct_Nova_Node) * 1);
	l1_Nova_temp[0] = this;
	return nova_standard_datastruct_list_Nova_Array_2_Nova_Array(0, exceptionData, (nova_standard_Nova_Object**)(l1_Nova_temp), 1);
}

void nova_standard_datastruct_Nova_Node_Nova_testLambda24(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_Nova_Node* nova_standard_datastruct_Nova_Node_Nova__1, int nova_standard_datastruct_Nova_Node_Nova__2, nova_standard_datastruct_list_Nova_Array* nova_standard_datastruct_Nova_Node_Nova__3, Context5* context)
{
	nova_standard_datastruct_list_Nova_Queue_Nova_enqueue((*context->nova_standard_datastruct_Nova_Node_Nova_queue), exceptionData, (nova_standard_Nova_Object*)(nova_standard_datastruct_Nova_Node_Nova__1));
}

void nova_standard_datastruct_Nova_Node_Nova_super(nova_standard_datastruct_Nova_Node* this, nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	this->nova_standard_datastruct_Nova_Node_Nova_data = (nova_standard_Nova_Object*)nova_null;
	this->nova_standard_datastruct_Nova_Node_Nova_children = (nova_standard_datastruct_list_Nova_Array*)nova_null;
}

