#include <precompiled.h>
#include <nova/standard/datastruct/list/nova_standard_datastruct_list_Nova_List.h>

nova_standard_datastruct_list_Extension_VTable_List nova_standard_datastruct_list_Extension_VTable_List_val =
{
	{
		0,
		0,
		0,
		0,
		0,
		0,
		(void(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_list_Nova_List_closure3_Nova_func nova_standard_datastruct_list_Nova_List_Nova_func, void* nova_standard_datastruct_list_Nova_List_ref_Nova_func))nova_standard_datastruct_list_Nova_List_0_Nova_forEach,
		(nova_standard_datastruct_list_Nova_List*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_list_Nova_List_closure6_Nova_mapFunc nova_standard_datastruct_list_Nova_List_Nova_mapFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_mapFunc))nova_standard_datastruct_list_Nova_List_0_Nova_map,
		(char(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_list_Nova_List_closure9_Nova_anyFunc nova_standard_datastruct_list_Nova_List_Nova_anyFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_anyFunc))nova_standard_datastruct_list_Nova_List_0_Nova_any,
		(char(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_list_Nova_List_closure12_Nova_allFunc nova_standard_datastruct_list_Nova_List_Nova_allFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_allFunc))nova_standard_datastruct_list_Nova_List_0_Nova_all,
		(nova_standard_datastruct_list_Nova_List*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc nova_standard_datastruct_list_Nova_List_Nova_filterFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_filterFunc))nova_standard_datastruct_list_Nova_List_0_Nova_filter,
		(nova_standard_datastruct_list_Nova_List*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, int))nova_standard_datastruct_list_Nova_List_0_Nova_take,
		(nova_standard_datastruct_list_Nova_List*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, int))nova_standard_datastruct_list_Nova_List_0_Nova_skip,
		(nova_standard_Nova_Object*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*))nova_standard_datastruct_list_Nova_List_0_Nova_first,
		(nova_standard_Nova_Object*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*))nova_standard_datastruct_list_Nova_List_0_Nova_last,
		(nova_standard_Nova_Object*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_datastruct_list_Nova_List_closure18_Nova_func nova_standard_datastruct_list_Nova_List_Nova_func, void* nova_standard_datastruct_list_Nova_List_ref_Nova_func))nova_standard_datastruct_list_Nova_List_0_Nova_firstWhere,
		(nova_standard_Nova_String*(*)(nova_standard_datastruct_list_Nova_List*, nova_standard_exception_Nova_ExceptionData*, nova_standard_Nova_String*))nova_standard_datastruct_list_Nova_List_0_Nova_join,
		0,
		0,
		0,
		0,
		0,
		0,
	},
	nova_standard_datastruct_list_Nova_List_0_Nova_forEach,
	nova_standard_datastruct_list_Nova_List_0_Nova_map,
	nova_standard_datastruct_list_Nova_List_0_Nova_any,
	nova_standard_datastruct_list_Nova_List_0_Nova_all,
	nova_standard_datastruct_list_Nova_List_0_Nova_filter,
	nova_standard_datastruct_list_Nova_List_0_Nova_take,
	nova_standard_datastruct_list_Nova_List_0_Nova_skip,
	nova_standard_datastruct_list_Nova_List_0_Nova_first,
	nova_standard_datastruct_list_Nova_List_0_Nova_last,
	nova_standard_datastruct_list_Nova_List_0_Nova_firstWhere,
	nova_standard_datastruct_list_Nova_List_0_Nova_join,
};


void nova_standard_datastruct_list_Nova_ListNova_init_static(nova_standard_exception_Nova_ExceptionData* exceptionData)
{
	{
	}
}

void nova_standard_datastruct_list_Nova_List_0_Nova_forEach(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_List_closure3_Nova_func nova_standard_datastruct_list_Nova_List_Nova_func, void* nova_standard_datastruct_list_Nova_List_ref_Nova_func){}
nova_standard_datastruct_list_Nova_List* nova_standard_datastruct_list_Nova_List_0_Nova_map(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_List_closure6_Nova_mapFunc nova_standard_datastruct_list_Nova_List_Nova_mapFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_mapFunc){return 0;}
char nova_standard_datastruct_list_Nova_List_0_Nova_any(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_List_closure9_Nova_anyFunc nova_standard_datastruct_list_Nova_List_Nova_anyFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_anyFunc){return 0;}
char nova_standard_datastruct_list_Nova_List_0_Nova_all(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_List_closure12_Nova_allFunc nova_standard_datastruct_list_Nova_List_Nova_allFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_allFunc){return 0;}
nova_standard_datastruct_list_Nova_List* nova_standard_datastruct_list_Nova_List_0_Nova_filter(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_List_closure15_Nova_filterFunc nova_standard_datastruct_list_Nova_List_Nova_filterFunc, void* nova_standard_datastruct_list_Nova_List_ref_Nova_filterFunc){return 0;}
nova_standard_datastruct_list_Nova_List* nova_standard_datastruct_list_Nova_List_0_Nova_take(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int nova_standard_datastruct_list_Nova_List_Nova_howMany){return 0;}
nova_standard_datastruct_list_Nova_List* nova_standard_datastruct_list_Nova_List_0_Nova_skip(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, int nova_standard_datastruct_list_Nova_List_Nova_howMany){return 0;}
nova_standard_Nova_Object* nova_standard_datastruct_list_Nova_List_0_Nova_first(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData){return 0;}
nova_standard_Nova_Object* nova_standard_datastruct_list_Nova_List_0_Nova_last(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData){return 0;}
nova_standard_Nova_Object* nova_standard_datastruct_list_Nova_List_0_Nova_firstWhere(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_datastruct_list_Nova_List_closure18_Nova_func nova_standard_datastruct_list_Nova_List_Nova_func, void* nova_standard_datastruct_list_Nova_List_ref_Nova_func){return 0;}
nova_standard_Nova_String* nova_standard_datastruct_list_Nova_List_0_Nova_join(nova_standard_datastruct_list_Nova_List* this, nova_standard_exception_Nova_ExceptionData* exceptionData, nova_standard_Nova_String* nova_standard_datastruct_list_Nova_List_Nova_delimiter){return 0;}
