name: Airship / Test Airship

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 5 * * *"

env:
  LOGGING_DEFAULT_SHOW_PREFIX: true
  LOGGING_DEFAULT_LOGGING_LEVEL: TRACE
  LOGGING_DEFAULT_SHOW_FORMATTING: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [js, es6]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 11

      - uses: actions/checkout@v4

      - name: Link monorepo packages for Airship
        uses: ./.github/actions/setup-flat-monorepo

      - name: Download latest Airship
        uses: ./.github/actions/download-airship
        with:
          repo: ${{ github.repository }}
          includePrerelease: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build Airship ${{ matrix.target }}
        run: |
          node airship.js --use-links -f packages/Airship install -t ${{ matrix.target }}

      - name: Delete Airship artifact
        run: |
          rm airship.js

      - name: Build Airship with Airship ${{ matrix.target }}
        run: |
          node packages/Airship/dist/airship.js --use-links -f packages/Airship install -t ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: airship.js
          path: packages/Airship/dist/airship.js

      - name: Build Airship Tests with Airship ${{ matrix.target }}
        run: |
          node packages/Airship/dist/airship.js --use-links -f packages/Airship install test -t ${{ matrix.target }}

      - name: Run Airship Tests
        run: |
          node packages/Airship/dist/airship.js --use-links -f packages/Airship run test -t ${{ matrix.target }}

      - name: Build Stability-Test with Airship ${{ matrix.target }}
        run: |
          node packages/Airship/dist/airship.js --use-links -f packages/Stability-Test install test -t ${{ matrix.target }}

      - name: Run Stability-Test
        run: |
          node packages/Stability-Test/dist/${{ matrix.target }}/test.js
