name: Build Flat

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout Flat Testing
        uses: actions/checkout@master
        with:
          repository: BSteffaniak/Flat-Testing
          path: Flat-Testing

      - name: Checkout Flat JS Writer
        uses: actions/checkout@master
        with:
          repository: FlatLang/Flat-js
          path: Flat-JS

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build CLI
        run: |
          mvn install

      - name: Build JS Writer
        run: |
          mvn -f Flat-JS install

      - name: Checkout Standard library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Standard-Library
          path: Standard-Library

      - name: Checkout Nest library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Nest
          path: Nest

      - name: Checkout Astro library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Astro
          path: Astro

      - name: Checkout Flatc library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Flatc
          path: Flatc

      - name: Checkout Spectra library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Spectra
          path: Spectra

      - name: Checkout Nebula library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Nebula
          path: Nebula

      - name: Checkout Compiler-String-Extensions library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Compiler-String-Extensions
          path: Compiler-String-Extensions

      - name: Checkout Network library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Network
          path: Network

      - name: Checkout MySQL library
        uses: actions/checkout@master
        with:
          repository: FlatLang/MySQL
          path: MySQL

      - name: Checkout Redis library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Redis
          path: Redis

      - name: Checkout Svg library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Svg
          path: Svg

      - name: Checkout Json library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Json
          path: Json

      - name: Checkout Stability-Test library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Stability-Test
          path: Stability-Test

      - name: Checkout SimpleGapRuleFlat
        uses: actions/checkout@master
        with:
          repository: BSteffaniak/SimpleGapRuleFlat
          path: SimpleGapRuleFlat

      - name: Build Stability Test
        working-directory: Stability-Test
        run: |
          java -jar ../target/flatc.jar \
            src \
            ../Flat-Testing/example \
            ../Astro \
            ../Flatc \
            ../Spectra \
            ../Nebula \
            ../SimpleGapRuleFlat \
            -l ../Nest \
            -l ../Compiler-String-Extensions \
            -l ../Network \
            -l ../MySQL \
            -l ../Redis \
            -l ../Svg \
            -l ../Json \
            -l ../IO \
            -l ../Time \
            -l ../Standard-Library \
            -install-dir .. \
            -main stabilitytest/StabilityTest \
            -o dist/test.js \
            -target js

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test.js
          path: dist/test.js

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Run Stability Test
        working-directory: Stability-Test
        run: |
          node dist/test.js

      - name: Build SimpleGapRule Test
        run: |
          java -jar target/flatc.jar \
            SimpleGapRuleFlat \
            -l Nest \
            -l Json \
            -l Compiler-String-Extensions \
            -l ../IO \
            -l ../Time \
            -l Standard-Library \
            -install-dir . \
            -main simplegaprule/AllTestsRunner \
            -o ./SimpleGapRuleFlat/SimpleGapRuleTests \
            -target js

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: SimpleGapRuleTests.js
          path: SimpleGapRuleFlat/SimpleGapRuleTests.js

      - name: Run SimpleGapRule Test
        working-directory: SimpleGapRuleFlat
        run: |
          node ./SimpleGapRuleTests.js
