name: Build Standard Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout Flat CLI
        uses: actions/checkout@master
        with:
          repository: FlatLang/Flat
          path: Flat

      - name: Checkout Flat Testing
        uses: actions/checkout@master
        with:
          repository: BSteffaniak/Flat-Testing
          path: Flat-Testing

      - name: Checkout Flat JS Writer
        uses: actions/checkout@master
        with:
          repository: FlatLang/Flat-js
          path: Flat-JS

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build CLI
        run: |
          mvn -f Flat install

      - name: Build JS Writer
        run: |
          mvn -f Flat-JS install

      - name: Checkout Nest library
        uses: actions/checkout@master
        with:
          repository: FlatLang/Nest
          path: Nest

      - name: Build Stability Test
        run: |
          java -jar Flat/target/flat-cli-1.0-SNAPSHOT-jar-with-dependencies.jar \
            Flat-Testing/example Flat-Testing/stabilitytest \
            -l Nest \
            -install-dir . \
            -std-path flatlang \
            -main stabilitytest/StabilityTest \
            -o Flat-Testing/example/bin/ExecutableJS \
            -target js

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ExecutableJS.js
          path: Flat-Testing/example/bin/ExecutableJS.js

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Run Stability Test
        run: |
          node Flat-Testing/example/bin/ExecutableJS.js
