name: Create Nightly Flat Release

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  create-nightly-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}

      - name: Get Tag Name
        id: tag_name
        run: |
          echo "::set-output name=TAG_NAME::${GITHUB_REF##*/}-nightly-$(date +%Y-%m-%d)"

      - name: Create and push tag
        run: |
          git tag ${{ steps.tag_name.outputs.TAG_NAME }}
          git push origin ${{ steps.tag_name.outputs.TAG_NAME }}

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tag_pattern: -nightly-
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}
