name: Flat / Build Flat

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 5 * * *"

env:
  LOGGING_DEFAULT_SHOW_PREFIX: true
  LOGGING_DEFAULT_LOGGING_LEVEL: TRACE
  LOGGING_DEFAULT_SHOW_FORMATTING: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Flat Testing
        uses: actions/checkout@v4
        with:
          repository: BSteffaniak/Flat-Testing
          path: Flat-Testing

      - name: Checkout SimpleGapRuleFlat
        uses: actions/checkout@v4
        with:
          repository: BSteffaniak/SimpleGapRuleFlat
          path: SimpleGapRuleFlat

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download latest Airship
        uses: ./.github/actions/download-airship
        with:
          repo: ${{ github.repository }}
          includePrerelease: true

      - name: Link monorepo packages for Airship
        uses: ./.github/actions/setup-flat-monorepo
        with:
          prebuild-targets: js

      - name: Build CLI under test
        run: |
          mvn -f packages/Flat/pom.xml install

      - name: Build current Airship
        run: |
          node airship.js --use-links -f packages/Airship install -t js

      - name: Build Stability Test
        run: |
          node packages/Airship/dist/airship.js --use-links \
            -f packages/Stability-Test install test -t js \
            --flatc-jar packages/Flat/target/flatc.jar

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: stability-test.js
          path: packages/Stability-Test/dist/js/test.js

      - name: Run Stability Test
        run: |
          node packages/Airship/dist/airship.js \
            -f packages/Stability-Test run test -t js

      - name: Compile Flat Testing sources
        working-directory: Flat-Testing
        run: |
          node ../packages/Airship/dist/airship.js --use-links \
            install test -t js \
            --flatc-jar ../packages/Flat/target/flatc.jar

      - name: Build SimpleGapRule Test
        working-directory: SimpleGapRuleFlat
        run: |
          node ../packages/Airship/dist/airship.js --use-links \
            install test -t js \
            --flatc-jar ../packages/Flat/target/flatc.jar

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: SimpleGapRuleTests.js
          path: SimpleGapRuleFlat/dist/js/test.js

      - name: Run SimpleGapRule Test
        working-directory: SimpleGapRuleFlat
        run: |
          node ../packages/Airship/dist/airship.js run test -t js
